create table public.tracker_users (
  id text primary key,
  name text not null check (char_length(name) between 1 and 20),
  role text not null check (char_length(role) between 1 and 30),
  avatar_bg text not null check (char_length(avatar_bg) between 1 and 80),
  initial_weight numeric(5,1) not null check (initial_weight between 45.0 and 140.0),
  target_weight numeric(5,1) not null check (target_weight between 45.0 and 140.0),
  motto text not null default '' check (char_length(motto) <= 120),
  updated_at timestamptz not null default now(),
  constraint tracker_users_fixed_ids check (id in ('liugang', 'zhangtinglei', 'luxuan')),
  constraint tracker_users_target_below_initial check (target_weight < initial_weight)
);

create table public.weight_entries (
  id bigint generated by default as identity primary key,
  user_id text not null references public.tracker_users(id) on update cascade on delete restrict,
  entry_date date not null check (entry_date between date '2026-08-24' and date '2026-09-30'),
  session text not null check (session in ('morning', 'evening')),
  weight numeric(5,1) not null check (weight between 45.0 and 140.0),
  note text not null default '' check (char_length(note) <= 200),
  is_retroactive boolean not null default false,
  recorded_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint weight_entries_one_per_session unique (user_id, entry_date, session)
);

create index weight_entries_date_idx
  on public.weight_entries (entry_date desc, user_id);

create table public.penalties (
  id bigint generated by default as identity primary key,
  user_id text not null references public.tracker_users(id) on update cascade on delete restrict,
  penalty_date date not null check (penalty_date between date '2026-08-24' and date '2026-09-30'),
  type text not null default '俯卧撑' check (char_length(type) between 1 and 40),
  count integer not null default 50 check (count between 1 and 10000),
  reason text not null check (char_length(reason) between 1 and 120),
  settled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index penalties_date_idx
  on public.penalties (penalty_date desc, created_at desc);

insert into public.tracker_users
  (id, name, role, avatar_bg, initial_weight, target_weight, motto)
values
  ('liugang', '刘钢', '主基准战士', 'from-emerald-500 to-teal-700', 96.0, 90.0, '守住底线，早晚如实打卡，绝不放弃！'),
  ('zhangtinglei', '张庭磊', '铁三角核心', 'from-cyan-500 to-blue-700', 90.0, 86.0, '严格自律，执行到底，相互督促！'),
  ('luxuan', '卢轩', '铁三角先锋', 'from-amber-500 to-orange-700', 94.0, 90.0, '兄弟同行，说到做到，共同达成！');

alter table public.tracker_users enable row level security;
alter table public.weight_entries enable row level security;
alter table public.penalties enable row level security;

revoke all on table public.tracker_users from anon, authenticated;
revoke all on table public.weight_entries from anon, authenticated;
revoke all on table public.penalties from anon, authenticated;
revoke all on sequence public.weight_entries_id_seq from anon, authenticated;
revoke all on sequence public.penalties_id_seq from anon, authenticated;

grant usage on schema public to anon, authenticated;
grant select on table public.tracker_users to anon, authenticated;
grant update (initial_weight, target_weight, motto, updated_at)
  on table public.tracker_users to anon, authenticated;
grant select, insert, update on table public.weight_entries to anon, authenticated;
grant select, insert, update on table public.penalties to anon, authenticated;
grant usage, select on sequence public.weight_entries_id_seq to anon, authenticated;
grant usage, select on sequence public.penalties_id_seq to anon, authenticated;

create policy "Public can read tracker users"
  on public.tracker_users
  for select
  to anon, authenticated
  using (true);

create policy "Public can update tracker profiles"
  on public.tracker_users
  for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "Public can read weight entries"
  on public.weight_entries
  for select
  to anon, authenticated
  using (true);

create policy "Public can add weight entries"
  on public.weight_entries
  for insert
  to anon, authenticated
  with check (true);

create policy "Public can update weight entries"
  on public.weight_entries
  for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "Public can read penalties"
  on public.penalties
  for select
  to anon, authenticated
  using (true);

create policy "Public can add penalties"
  on public.penalties
  for insert
  to anon, authenticated
  with check (true);

create policy "Public can update penalties"
  on public.penalties
  for update
  to anon, authenticated
  using (true)
  with check (true);
